### ISSUE TITLE
Video position bookmarking feature?

### ISSUE THREAD

**Issue by klorinczi** [OpenViX/vix-core#130]
Hello!

I have VU+ DUO 4K SE PVR, installed OpenVIX, but I did not find video position bookmarking feature. 

By bookmark I mean placing position marks (jump points) into the video recording.
Using this I could jump to any bookmarked point/location within the video during the playback.

Could be possible to implement such video bookmarking (jump points) feature?

Thanks!

**Comment by Huevos** [comment]
Nothing to do with this plugin. If you still have a problem you should report it on the forum.
https://www.world-of-satellite.com/
