### ISSUE TITLE
Old CCcam installed with OpenViX 5.2

### ISSUE THREAD

**Issue by EGGMANCAN** [OpenViX/vix-core#43]
Currently CCcam 2.3.0 is installed on OpenViX V5.2. 
The latest CCcam is "enigma2-softcams-cccam-all-images_2.3.2-r1_arm-mips_all.ipk".
This version is supposed to work with ARM and MIPS processors. 
Can we have this pre-installed on the latest OpenViX image.
Can we include it in OpenViX plugin downloads also?

**Comment by EGGMANCAN** [comment]
Also oscam-latest is the only oscam that works for me on ARM Octagon SF8008. OSCam.r9059 does not work and the links at http://www.openvix.co.uk/index.php/downloads/softcams/ need to be updated.

**Comment by ViX-Sicilian** [comment]
They are old softcams that will actually be removed from the site soon. Kindly post about request like this on the forum, not on Github. Forum reports will suffice.

**Comment by Huevos** [comment]
Yes, please only post issues on Github that are actually related to code hosted on Github.

**Comment by EGGMANCAN** [comment]
When I installed OpenViX latest version on my Octagon SF8008 the old versions of CCcam and OScam are installed and they don't work! The Octagon SF8008 is an ARM receiver and the OScam that is installed by-default is not compatible. Can we make "oscam-latest" the default OScam installed with the Octagon SF8008 image release please? and also "enigma2-softcams-cccam-all-images_2.3.2-r1_arm-mips_all.ipk". 
Remove the other softcams from the Octagon SF8008 ViX images because they do not work.

**Comment by ViX-Sicilian** [comment]
OpenViX does not pre-install ANY softcams. Oscam-latest is in the plugin feeds. Git hub is not the place for this discussion.
