### ISSUE TITLE
Softcam config file locations

### ISSUE THREAD

**Issue by EGGMANCAN** [OpenViX/vix-core#44]
If you use OpenATV then your oscam folder location is:
/etc/tuxbox/config/oscam/
but if you use OpenViX then the location is:
/usr/keys/oscam/
Can we support BOTH locations on OpenViX to prevent file/folder duplications? 

Also on OpenATV your CCcam.cfg location is:
/usr/keys/CCcam.cfg
and OpenViX is:
/etc/CCcam.cfg
Can we add support for both locations?

**Comment by EGGMANCAN** [comment]
Would this work?
SoftcamManager.py:
`line 291: if selectedcam.lower().startswith('cccam') and path.exists('/etc/CCcam.cfg') == True:`

`line 291: if selectedcam.lower().startswith('cccam') and path.exists('/etc/CCcam.cfg') or ('/usr/keys/CCcam.cfg') == True:`

**Comment by ViX-Sicilian** [comment]
Use the forum.

**Comment by EGGMANCAN** [comment]
> 
> 
> Use the forum.

use the forum for what? why do we need 2+ directories for the same files? why does ViX have to use /usr/keys/oscam/ and OpenATV use /etc/tuxbox/config/oscam/? why not support both locations? it would be a simple fix...

**Comment by AbuBaniaz** [comment]
You are mistaken. We don't use the keys folder for Oscam.
